language: php

php:
    - 5.6

before_script:
    - COMPOSER_ROOT_VERSION=dev-master composer install --dev --prefer-source

script: vendor/bin/phpunit

notifications:
  email: false

after_script:
  - php vendor/bin/coveralls
